#!/usr/bin/env python3
"""Generate the ELF-style linker script (original section names, VMAs, LMAs, PHDRS).

The objects are the same ones the splat ROM-style script links; each object line of
`<unit>.ld` is mapped to the original output section it belongs to (by input
section name, plus object name for sections splat only knows as `.data`).  Every
allocated section is pinned at its original address (slinky-style), so a C object
that changes size shows up as a layout error instead of silently shifting code.

    link_elf.py <unit_dir> <unit> --flavor modern|legacy
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from elfinfo import Elf  # noqa: E402

DATA_BY_OBJECT = {"reginfo": ".reginfo", "ctors": ".ctors", "dtors": ".dtors",
                  "eh_frame": ".eh_frame", "vudata": ".vudata"}
DISCARD = ["*(.reginfo)", "*(.MIPS.abiflags)", "*(.pdr)", "*(.gnu.attributes)",
           "*(.mdebug*)", "*(.comment)", "*(.note*)"]


def target_section(obj, insec, unit, overlay_name):
    stem = Path(obj).name.split(".")[0]
    if overlay_name and (f"/{overlay_name}/" in obj or unit != "main"):
        return overlay_name
    if insec == ".data" and stem in DATA_BY_OBJECT:
        return DATA_BY_OBJECT[stem]
    return insec


def generate(unit_dir, unit, flavor, main_symbols=None):
    yaml = (unit_dir / "splat.yaml").read_text()
    orig = Elf((unit_dir / re.search(r"target_path: (\S+)", yaml)[1]).read_bytes())
    rom_ld = (unit_dir / f"{unit}.ld").read_text()
    legacy = flavor == "legacy"
    overlay = next((s.name for s in orig.sections if s.name.startswith("ov") and s.flags & 2), None)
    inputs = {}
    last = None
    for obj, insec, pad in re.findall(r"(build/[\w/.\-]+\.o)\((\.\w+)\);|(\. \+= 0x[0-9A-Fa-f]+;)", rom_ld):
        if pad:
            # splat `pad` subsegment: inside an overlay section it is part of the
            # section (e.g. OV10's 2-byte tail); in MAIN pads are inter-section gaps
            # that the pinned section addresses reproduce by themselves.
            if last == overlay and overlay is not None:
                inputs[last].append(pad[:-1])
            continue
        if obj.startswith("build/assets/") and Path(obj).stem != "reginfo":
            continue  # ELF header / metadata blobs are produced by the linker itself here
        last = target_section(obj, insec, unit, overlay)
        inputs.setdefault(last, []).append(f"{obj}({insec})")
    alloc = sorted((s for s in orig.sections if s.flags & 2), key=lambda s: (s.addr, s.index))
    # entry point: passed as `-e 0x...` on the ld command line (the ELF header value)
    lines = ["/* Generated by tools/link_elf.py (TU-migration prototype): ELF-style link */"]
    if orig.gp is not None:
        lines.append(f"_gp = 0x{orig.gp:08X};")
    phdrs = []
    for i, p in enumerate(orig.phdrs):
        kind = {1: "PT_LOAD", 0x70000000: "0x70000000"}[p.type]
        # OV02/OV10/OV12: the original PT_LOAD starts at file offset 0 and maps the
        # ELF/program headers too (p_vaddr = 0x9ff000); reproduce that explicitly.
        hdr = " FILEHDR PHDRS" if p.type == 1 and p.offset == 0 else ""
        phdrs.append(f"  seg{i} {kind}{hdr} FLAGS({p.flags});")
    lines += ["PHDRS", "{", *phdrs, "}", "SECTIONS", "{"]
    for s in alloc:
        segs = [i for i, p in enumerate(orig.phdrs) if p.vaddr <= s.addr <= p.vaddr + p.memsz
                and (p.type == 1 or (s.name == ".reginfo" and s.addr == p.vaddr))]
        loads = [i for i in segs if orig.phdrs[i].type == 1]
        ph = orig.phdrs[loads[0]]
        lma = ph.paddr + s.addr - ph.vaddr
        qual = " (NOLOAD)" if s.type == 8 else ""
        if s.name == ".reginfo" and not legacy:
            qual = " (TYPE = 0x70000006)"
        at = f" AT(0x{lma:X})" if s.type != 8 else ""
        if not legacy:
            at += f" ALIGN({s.align})"  # original sh_addralign (address is pinned anyway)
        lines.append(f"  {s.name} 0x{s.addr:X}{qual} :{at}")
        lines.append("  {")
        for item in inputs.get(s.name, []):
            lines.append(f"    {item};")
        if not inputs.get(s.name) and not legacy:
            lines.append("    . = .;  /* keep the empty original section */")
        order = [loads[0]] + [i for i in segs if i != loads[0]]
        lines.append("  } " + " ".join(f":seg{i}" for i in order))
    placed = {s.name for s in alloc}
    extra = sorted(set(inputs) - placed)
    if extra:
        raise SystemExit(f"objects map to sections absent from the original: {extra}")
    lines += ["  /DISCARD/ : { " + " ".join(DISCARD) + " }", "}", ""]
    out = unit_dir / f"{unit}.elf.{flavor}.ld"
    out.write_text("\n".join(lines))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("unit_dir", type=Path)
    ap.add_argument("unit")
    ap.add_argument("--flavor", choices=("modern", "legacy"), default="modern")
    a = ap.parse_args()
    print(generate(a.unit_dir, a.unit, a.flavor))


if __name__ == "__main__":
    main()
