/* Generated by tools/header_harvest.py. Do not edit by hand. */
/*
 * Public declarations of the translation unit main/tu099 (src/main/xgl_hdd.c):
 * what this TU defines and at least one other published TU needs. The
 * definition wins, so this is where the project states these prototypes.
 * Regenerate with `python3 tools/header_harvest.py`.
 */

#ifndef INCLUDE_MAIN_XGL_HDD_H
#define INCLUDE_MAIN_XGL_HDD_H

int xglHddMount(void);

#endif /* INCLUDE_MAIN_XGL_HDD_H */
