name: xenosaga1 ov01 TU-migration phase 2 (per original TU)
sha1: 4da60dd224f30c1e573a3968320690aaed881f98
options:
  platform: ps2
  compiler: EEGCC
  endianness: little
  base_path: .
  target_path: orig/OV01.OVL
  basename: ov01
  asm_path: asm
  src_path: scaffold/src
  auto_decompile_empty_functions: False
  disassemble_all: True
  build_path: build
  asset_path: assets
  ld_script_path: ov01.ld
  symbol_addrs_path:
    - symbol_addrs.txt
  undefined_funcs_auto_path: undefined_funcs_auto.txt
  undefined_syms_auto_path: undefined_syms_auto.txt
  o_as_suffix: True
  create_asm_dependencies: False
  ld_dependencies: False
  find_file_boundaries: False
  disasm_unknown: True
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  named_regs_for_c_funcs: False
  mips_abi_gpr: numeric
  mips_abi_float_regs: numeric
  generate_asm_macros_files: True
  asm_function_macro: glabel
  asm_data_macro: dlabel
  asm_end_label: endlabel
  asm_emit_size_directive: True
  use_legacy_include_asm: False
  ld_fill_value: 0
  section_order:
    - .text
    - .data
    - .rodata
    - .lit4
    - .sdata
    - .sbss
    - .bss
  migrate_rodata_to_functions: False
segments:
  - [0x0, bin, elf_header]
  - name: ov01
    type: code
    start: 0x1000
    vram: 0x00A00000
    bss_size: 0x9F88
    align: 4
    subalign: null
    subsegments:
      - [0x1000, c, ov01/yamamoto_test]
      - [0x1218, c, ov01/obj]
      - [0x1D60, c, ov01/unit_cmd]
      - [0x8770, c, ov01/battle_init]
      - [0x11BB8, c, ov01/calc]
      - [0x1A1C0, c, ov01/data_unit_org_get]
      - [0x1E348, c, ov01/cmd]
      - [0x23628, c, ov01/entry_first_init]
      - [0x25A98, c, ov01/gr_gp_init]
      - [0x27018, c, ov01/menu]
      - [0x2D3A0, c, ov01/map_disp]
      - [0x2D5A8, c, ov01/data_eth_name_get]
      - [0x2D9B8, c, ov01/result]
      - [0x2D9F8, c, ov01/snd]
      - [0x2F4B0, c, ov01/debug_entry]
      - [0x32340, c, ov01/matuzawa_test]
      - [0x32348, c, ov01/m_battle]
      - [0x324B8, c, ov01/m_cam]
      - [0x33DB8, c, ov01/m_gs]
      - [0x33E78, c, ov01/m_mv]
      - [0x342E0, c, ov01/m_mv2]
      - [0x34648, c, ov01/m_ef_create]
      - [0x347A0, c, ov01/m_ef]
      - [0x34F08, c, ov01/m_ef_create_msp_00]
      - [0x356C8, c, ov01/m_ef_create_bp_00]
      - [0x35E90, c, ov01/m_ef_create_smp_01]
      - [0x368A0, c, ov01/m_ef_create_eac_00]
      - [0x368A8, c, ov01/m_ef_create_amp_02]
      - [0x370E0, c, ov01/m_ef_create_msp_02]
      - [0x37BE8, c, ov01/m_ef_create_solb]
      - [0x38AB8, c, ov01/m_ef_create_ecm_01]
      - [0x39190, c, ov01/m_ef_create_ecm_02]
      - [0x397A8, c, ov01/m_ef_create_gamera]
      - [0x3A088, c, ov01/m_ef_create_ead_00]
      - [0x3A7C0, c, ov01/m_ef_create_so_14]
      - [0x3A7C8, c, ov01/m_ef_create_dora]
      - [0x3B090, c, ov01/m_ef_create_kosbw_02]
      - [0x3BAC8, data, ov01/unit_cmd]
      - [0x3E440, data, ov01/battle_init]
      - [0x3E8F8, data, ov01/calc]
      - [0x3E980, data, ov01/data_unit_org_get]
      - [0x3FDC8, data, ov01/cmd]
      - [0x3FF60, data, ov01/entry_first_init]
      - [0x40000, data, ov01/gr_gp_init]
      - [0x40038, data, ov01/menu]
      - [0x407E0, data, ov01/map_disp]
      - [0x407E8, data, ov01/data_eth_name_get]
      - [0x434B8, data, ov01/snd]
      - [0x43DC0, data, ov01/debug_entry]
      - [0x4468C, data, ov01/m_battle]
      - [0x44690, data, ov01/m_mv]
      - [0x44724, data, ov01/m_mv2]
      - [0x44728, data, ov01/m_ef_create]
      - [0x44780, data, ov01/m_ef_create_solb]
      - [0x447B0, data, ov01/m_ef_create_ead_00]
      - [0x447E0, rodata, ov01/obj]
      - [0x448F0, rodata, ov01/unit_cmd]
      - [0x44C20, rodata, ov01/battle_init]
      - [0x45310, rodata, ov01/calc]
      - [0x45880, rodata, ov01/data_unit_org_get]
      - [0x47050, rodata, ov01/cmd]
      - [0x475E0, rodata, ov01/entry_first_init]
      - [0x476E8, rodata, ov01/gr_gp_init]
      - [0x47730, rodata, ov01/menu]
      - [0x47C18, rodata, ov01/map_disp]
      - [0x47C28, rodata, ov01/data_eth_name_get]
      - [0x4F130, rodata, ov01/snd]
      - [0x4F880, rodata, ov01/debug_entry]
      - [0x51EA8, rodata, ov01/m_battle]
      - [0x51EC8, rodata, ov01/m_cam]
      - [0x520A0, rodata, ov01/m_mv]
      - [0x52160, rodata, ov01/m_mv2]
      - [0x52220, rodata, ov01/m_ef_create]
      - [0x522B0, rodata, ov01/m_ef]
      - [0x52380, rodata, ov01/m_ef_create_msp_00]
      - [0x52460, rodata, ov01/m_ef_create_bp_00]
      - [0x52480, rodata, ov01/m_ef_create_smp_01]
      - [0x52580, rodata, ov01/m_ef_create_amp_02]
      - [0x52680, rodata, ov01/m_ef_create_msp_02]
      - [0x52780, rodata, ov01/m_ef_create_solb]
      - [0x527D0, rodata, ov01/m_ef_create_gamera]
      - [0x52820, rodata, ov01/m_ef_create_dora]
      - [0x52880, rodata, ov01/m_ef_create_kosbw_02]
      - [0x52970]
      - { type: bss, vram: 0x00A51970, name: ov01/obj }
      - { type: bss, vram: 0x00A57240, name: ov01/unit_cmd }
      - { type: bss, vram: 0x00A57300, name: ov01/battle_init }
      - { type: bss, vram: 0x00A57CE8, name: ov01/calc }
      - { type: bss, vram: 0x00A57E90, name: ov01/data_unit_org_get }
      - { type: bss, vram: 0x00A597D0, name: ov01/cmd }
      - { type: bss, vram: 0x00A5A1E8, name: ov01/entry_first_init }
      - { type: bss, vram: 0x00A5A250, name: ov01/gr_gp_init }
      - { type: bss, vram: 0x00A5A2A0, name: ov01/menu }
      - { type: bss, vram: 0x00A5A920, name: ov01/map_disp }
      - { type: bss, vram: 0x00A5A940, name: ov01/snd }
      - { type: bss, vram: 0x00A5AA40, name: ov01/debug_entry }
      - { type: bss, vram: 0x00A5AA70, name: ov01/m_cam }
      - { type: bss, vram: 0x00A5B630, name: ov01/m_mv }
      - { type: bss, vram: 0x00A5B7B0, name: ov01/m_mv2 }
  - [0x52970, pad, ov01_bss_file_image]
  - [0x5C8F8, bin, elf_shstrtab]
  - [0x5C918, bin, elf_section_headers]
  - [0x5C9E0, bin, elf_symtab]
  - [0x631C0, bin, elf_strtab]
  - [0x67C9A]
