/* Generated by tools/header_harvest.py. Do not edit by hand. */
/*
 * Public declarations of the translation unit ov01/tu001 (src/ov01/obj.c):
 * what this TU defines and at least one other published TU needs. The
 * definition wins, so this is where the project states these prototypes.
 * Regenerate with `python3 tools/header_harvest.py`.
 */

#ifndef INCLUDE_OV01_OBJ_H
#define INCLUDE_OV01_OBJ_H

#include "shared.h"

/* canon: config/header-canon.json chose src/core/ov01-00a00518/candidate.c over 1 other accepted spelling */
void objRemovePure(ObjectTask *task);

#endif /* INCLUDE_OV01_OBJ_H */
